name : Testing Main Releases

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Provide the release version'
        required: true

jobs:
  Testing_Releases:
    name: Testing Main Releases
    runs-on: self-hosted

    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Creating Releases
        id: release-tag-final
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
        with:
          tag_name: ${{ inputs.release }}
          release_name: ${{ inputs.release }}

      - name: coping readme file to s3 bucket
        run : aws s3 cp README.md s3://mskrishna2809
      - name: coping text file to s3 bucket
        run : aws s3 cp release.txt s3://mskrishna2809
